#!/usr/bin/env python3
"""
World English Bible Importer
Downloads and imports the complete World English Bible into SQL format
for use with the Bible Study application.

Usage:
    python3 import_bible.py

This will:
1. Download the USFX XML format from eBible.org
2. Parse the XML to extract book, chapter, verse, and text
3. Generate SQL INSERT statements
4. Create bible_import.sql file ready to run in Supabase
"""

import urllib.request
import zipfile
import xml.etree.ElementTree as ET
import os
import re

# Download URL for World English Bible in USFX format
BIBLE_URL = "https://eBible.org/Scriptures/engwebp_usfx.zip"
ZIP_FILE = "engwebp_usfx.zip"
EXTRACT_DIR = "bible_data"
OUTPUT_SQL = "bible_import.sql"

# Book name mappings (USFX uses abbreviations)
BOOK_NAMES = {
    'GEN': 'Genesis', 'EXO': 'Exodus', 'LEV': 'Leviticus', 'NUM': 'Numbers', 'DEU': 'Deuteronomy',
    'JOS': 'Joshua', 'JDG': 'Judges', 'RUT': 'Ruth', '1SA': '1 Samuel', '2SA': '2 Samuel',
    '1KI': '1 Kings', '2KI': '2 Kings', '1CH': '1 Chronicles', '2CH': '2 Chronicles',
    'EZR': 'Ezra', 'NEH': 'Nehemiah', 'EST': 'Esther', 'JOB': 'Job', 'PSA': 'Psalms', 'PRO': 'Proverbs',
    'ECC': 'Ecclesiastes', 'SNG': 'Song of Solomon', 'ISA': 'Isaiah', 'JER': 'Jeremiah', 'LAM': 'Lamentations',
    'EZK': 'Ezekiel', 'DAN': 'Daniel', 'HOS': 'Hosea', 'JOL': 'Joel', 'AMO': 'Amos', 'OBA': 'Obadiah',
    'JON': 'Jonah', 'MIC': 'Micah', 'NAM': 'Nahum', 'HAB': 'Habakkuk', 'ZEP': 'Zephaniah', 'HAG': 'Haggai',
    'ZEC': 'Zechariah', 'MAL': 'Malachi',
    'MAT': 'Matthew', 'MRK': 'Mark', 'LUK': 'Luke', 'JHN': 'John', 'ACT': 'Acts', 'ROM': 'Romans',
    '1CO': '1 Corinthians', '2CO': '2 Corinthians', 'GAL': 'Galatians', 'EPH': 'Ephesians',
    'PHP': 'Philippians', 'COL': 'Colossians', '1TH': '1 Thessalonians', '2TH': '2 Thessalonians',
    '1TI': '1 Timothy', '2TI': '2 Timothy', 'TIT': 'Titus', 'PHM': 'Philemon', 'HEB': 'Hebrews',
    'JAS': 'James', '1PE': '1 Peter', '2PE': '2 Peter', '1JN': '1 John', '2JN': '2 John', '3JN': '3 John',
    'JUD': 'Jude', 'REV': 'Revelation'
}

def download_bible():
    """Download the World English Bible ZIP file"""
    print(f"Downloading World English Bible from {BIBLE_URL}...")
    urllib.request.urlretrieve(BIBLE_URL, ZIP_FILE)
    print(f"Downloaded {ZIP_FILE}")

def extract_zip():
    """Extract the ZIP file"""
    print(f"Extracting {ZIP_FILE}...")
    with zipfile.ZipFile(ZIP_FILE, 'r') as zip_ref:
        zip_ref.extractall(EXTRACT_DIR)
    print(f"Extracted to {EXTRACT_DIR}/")

def clean_text(text):
    """Clean and escape text for SQL"""
    if not text:
        return ""
    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text).strip()
    # Escape single quotes for SQL
    text = text.replace("'", "''")
    return text

def parse_usfx_simple(xml_file):
    """Parse USFX XML file and extract verses (simplified approach)"""
    print(f"Parsing {xml_file}...")
    
    verses = []
    
    try:
        tree = ET.parse(xml_file)
        root = tree.getroot()
        
        current_book = None
        current_chapter = None
        
        # Walk through all elements
        for elem in root.iter():
            tag = elem.tag.split('}')[-1]  # Remove namespace
            
            # Book element
            if tag == 'book':
                book_id = elem.get('id', '').upper()
                current_book = BOOK_NAMES.get(book_id, book_id)
                print(f"  Processing {current_book}...")
            
            # Chapter element
            elif tag == 'c':
                current_chapter = elem.get('id')
            
            # Verse element
            elif tag == 'v':
                if current_book and current_chapter:
                    verse_id = elem.get('id')
                    # Get all text from this verse element
                    verse_text = ''.join(elem.itertext()).strip()
                    verse_text = clean_text(verse_text)
                    
                    if verse_text:
                        verses.append({
                            'book': current_book,
                            'chapter': int(current_chapter),
                            'verse': int(verse_id),
                            'text': verse_text
                        })
        
        print(f"Parsed {len(verses)} verses")
        return verses
        
    except Exception as e:
        print(f"Error parsing XML: {e}")
        return []

def generate_sql(verses):
    """Generate SQL INSERT statements"""
    print(f"Generating SQL statements...")
    
    sql_lines = [
        "-- World English Bible Import",
        "-- Generated by import_bible.py",
        "-- Total verses: " + str(len(verses)),
        "",
        "-- Clear existing data (optional - comment out if you want to keep sample data)",
        "-- DELETE FROM bible_verses;",
        "",
        "-- Insert verses",
        "BEGIN;",
        ""
    ]
    
    # Batch insert for better performance
    batch_size = 100
    for i in range(0, len(verses), batch_size):
        batch = verses[i:i+batch_size]
        
        sql_lines.append("INSERT INTO bible_verses (book_name, chapter, verse, text) VALUES")
        
        values = []
        for v in batch:
            values.append(f"  ('{v['book']}', {v['chapter']}, {v['verse']}, '{v['text']}')")
        
        sql_lines.append(',\n'.join(values) + ';')
        sql_lines.append("")
    
    sql_lines.append("COMMIT;")
    sql_lines.append("")
    sql_lines.append("-- Verify import")
    sql_lines.append("SELECT book_name, COUNT(*) as verse_count")
    sql_lines.append("FROM bible_verses")
    sql_lines.append("GROUP BY book_name")
    sql_lines.append("ORDER BY MIN(id);")
    
    return '\n'.join(sql_lines)

def main():
    """Main import process"""
    print("=" * 60)
    print("World English Bible Importer")
    print("=" * 60)
    print()
    
    # Step 1: Download
    if not os.path.exists(ZIP_FILE):
        download_bible()
    else:
        print(f"{ZIP_FILE} already exists, skipping download")
    
    # Step 2: Extract
    if not os.path.exists(EXTRACT_DIR):
        extract_zip()
    else:
        print(f"{EXTRACT_DIR} already exists, skipping extraction")
    
    # Step 3: Find USFX file
    usfx_file = None
    for root, dirs, files in os.walk(EXTRACT_DIR):
        for file in files:
            if file.endswith('.usfx'):
                usfx_file = os.path.join(root, file)
                break
    
    if not usfx_file:
        print("ERROR: Could not find .usfx file in extracted data")
        return
    
    # Step 4: Parse
    verses = parse_usfx_simple(usfx_file)
    
    if not verses:
        print("ERROR: No verses were parsed")
        return
    
    # Step 5: Generate SQL
    sql_content = generate_sql(verses)
    
    # Step 6: Write to file
    with open(OUTPUT_SQL, 'w', encoding='utf-8') as f:
        f.write(sql_content)
    
    print()
    print("=" * 60)
    print(f"SUCCESS! Created {OUTPUT_SQL}")
    print(f"Total verses: {len(verses)}")
    print()
    print("Next steps:")
    print(f"1. Open {OUTPUT_SQL} in a text editor to verify")
    print("2. Go to Supabase SQL Editor")
    print("3. Copy and paste the contents of bible_import.sql")
    print("4. Click 'Run' to import all verses")
    print("5. This may take 1-2 minutes to complete")
    print("=" * 60)

if __name__ == "__main__":
    main()
