#!/usr/bin/env node
/**
 * World English Bible Importer (Node.js version)
 * 
 * Usage: node import_bible_node.js
 * 
 * This will download and parse the World English Bible,
 * generating a SQL file ready to import into Supabase.
 */

const https = require('https');
const fs = require('fs');
const path = require('path');
const { XMLParser } = require('fast-xml-parser');

// If fast-xml-parser is not installed:
// npm install fast-xml-parser

const BIBLE_URL = 'https://eBible.org/Scriptures/engwebp_usfx.zip';
const ZIP_FILE = 'engwebp_usfx.zip';
const OUTPUT_SQL = 'bible_import.sql';

// Simplified approach: Use plain text files instead
const PLAIN_TEXT_URL = 'https://eBible.org/Scriptures/engwebp_readaloud.zip';

// Book name mappings
const BOOK_NAMES = {
  'GEN': 'Genesis', 'EXO': 'Exodus', 'LEV': 'Leviticus', 'NUM': 'Numbers', 'DEU': 'Deuteronomy',
  'JOS': 'Joshua', 'JDG': 'Judges', 'RUT': 'Ruth', '1SA': '1 Samuel', '2SA': '2 Samuel',
  '1KI': '1 Kings', '2KI': '2 Kings', '1CH': '1 Chronicles', '2CH': '2 Chronicles',
  'EZR': 'Ezra', 'NEH': 'Nehemiah', 'EST': 'Esther', 'JOB': 'Job', 'PSA': 'Psalms', 'PRO': 'Proverbs',
  'ECC': 'Ecclesiastes', 'SNG': 'Song of Solomon', 'ISA': 'Isaiah', 'JER': 'Jeremiah', 'LAM': 'Lamentations',
  'EZK': 'Ezekiel', 'DAN': 'Daniel', 'HOS': 'Hosea', 'JOL': 'Joel', 'AMO': 'Amos', 'OBA': 'Obadiah',
  'JON': 'Jonah', 'MIC': 'Micah', 'NAM': 'Nahum', 'HAB': 'Habakkuk', 'ZEP': 'Zephaniah', 'HAG': 'Haggai',
  'ZEC': 'Zechariah', 'MAL': 'Malachi',
  'MAT': 'Matthew', 'MRK': 'Mark', 'LUK': 'Luke', 'JHN': 'John', 'ACT': 'Acts', 'ROM': 'Romans',
  '1CO': '1 Corinthians', '2CO': '2 Corinthians', 'GAL': 'Galatians', 'EPH': 'Ephesians',
  'PHP': 'Philippians', 'COL': 'Colossians', '1TH': '1 Thessalonians', '2TH': '2 Thessalonians',
  '1TI': '1 Timothy', '2TI': '2 Timothy', 'TIT': 'Titus', 'PHM': 'Philemon', 'HEB': 'Hebrews',
  'JAS': 'James', '1PE': '1 Peter', '2PE': '2 Peter', '1JN': '1 John', '2JN': '2 John', '3JN': '3 John',
  'JUD': 'Jude', 'REV': 'Revelation'
};

function cleanText(text) {
  if (!text) return '';
  // Remove extra whitespace
  text = text.replace(/\s+/g, ' ').trim();
  // Escape single quotes for SQL
  text = text.replace(/'/g, "''");
  return text;
}

function generateSQL(verses) {
  console.log('Generating SQL...');
  
  let sql = `-- World English Bible Import
-- Generated by import_bible_node.js
-- Total verses: ${verses.length}

-- Clear existing data (optional - comment out if you want to keep sample data)
-- DELETE FROM bible_verses;

-- Insert verses
BEGIN;

`;

  // Batch inserts for better performance
  const batchSize = 100;
  for (let i = 0; i < verses.length; i += batchSize) {
    const batch = verses.slice(i, i + batchSize);
    
    sql += 'INSERT INTO bible_verses (book_name, chapter, verse, text) VALUES\n';
    
    const values = batch.map(v => 
      `  ('${v.book}', ${v.chapter}, ${v.verse}, '${v.text}')`
    );
    
    sql += values.join(',\n') + ';\n\n';
  }

  sql += `COMMIT;

-- Verify import
SELECT book_name, COUNT(*) as verse_count
FROM bible_verses
GROUP BY book_name
ORDER BY MIN(id);
`;

  return sql;
}

console.log('='.repeat(60));
console.log('World English Bible Importer (Node.js)');
console.log('='.repeat(60));
console.log();
console.log('MANUAL DOWNLOAD REQUIRED:');
console.log();
console.log('Due to parsing complexity, please use ONE of these methods:');
console.log();
console.log('METHOD 1: Use the Python script (Recommended)');
console.log('  python3 import_bible.py');
console.log();
console.log('METHOD 2: Use a pre-parsed Bible API');
console.log('  See: https://github.com/scrollmapper/bible_databases');
console.log('  Download the SQLite or CSV version');
console.log();
console.log('METHOD 3: Manual download and import');
console.log('  1. Download: https://github.com/scrollmapper/bible_databases');
console.log('  2. Get the CSV or SQL file for World English Bible');
console.log('  3. Import directly into Supabase');
console.log();
console.log('METHOD 4: Use sample data and add books as needed');
console.log('  The sample-data.sql already includes James 1, John 3, Psalm 23');
console.log('  You can manually add more chapters as your group needs them');
console.log();
console.log('='.repeat(60));
